inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyrax-iiif_av.gemspec'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'lib/hyrax/iiif_av/spec/shared_specs/controller_behavior.rb'
    - 'lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb'
    - 'lib/hyrax/iiif_av/spec/shared_specs/displays_iiif.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'lib/hyrax/iiif_av/spec/shared_specs/controller_behavior.rb'
    - 'lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb'

RSpec/ExampleLength:
  Exclude:
    - 'lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb'
