inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyrax-iiif_av.gemspec'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'lib/hyrax/iiif_av/spec/shared_specs/controller_behavior.rb'
    - 'lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb'
    - 'lib/hyrax/iiif_av/spec/shared_specs/displays_iiif_av.rb'
    - 'spec/controllers/generic_works_controller_spec.rb'
    - 'spec/controllers/iiif_av_controller_spec.rb'
    - 'spec/helpers/iiif_av_helper_spec.rb'
    - 'spec/requests/auth_controller_behavior_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'lib/hyrax/iiif_av/spec/shared_specs/controller_behavior.rb'
    - 'lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb'
    - 'spec/helpers/iiif_av_helper_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'lib/hyrax/iiif_av/spec/shared_specs/displays_content.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/presenters/concerns/hyrax/iiif_av/displays_content.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/presenters/concerns/hyrax/iiif_av/displays_content.rb'

Rails/OutputSafety:
  Exclude:
    - 'app/controllers/hyrax/iiif_av/iiif_av_controller.rb'
