inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyrax-iiif_av.gemspec'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/support/shared_examples/concerns/iiif_av/controller_behavior_spec.rb'
    - 'spec/support/shared_examples/concerns/iiif_av/displays_content_spec.rb'
    - 'spec/support/shared_examples/concerns/iiif_av/displays_iiif_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/support/shared_examples/concerns/iiif_av/controller_behavior_spec.rb'
    - 'spec/support/shared_examples/concerns/iiif_av/displays_content_spec.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/support/shared_examples/concerns/iiif_av/displays_content_spec.rb'
