inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'hyrax-iiif_av.gemspec'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'
