version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
        default: 2.5.5
      bundler_version:
        type: string
        default: 2.3.0
        
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>

    working_directory: ~/project

    environment:
      ENGINE_CART_RAILS_OPTIONS: --skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-coffee --skip-puma --skip-test
      
    steps:
      - samvera/cached_checkout
          
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
    
      - samvera/engine_cart_generate:
          cache_key: v2-internal-test-app-{{ checksum "hyrax-iiif_av.gemspec" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-{{ checksum "lib/generators/hyrax/iiif_av/install_generator.rb" }}

      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/conf

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          
      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_and_test:
          name: ruby2-7
          ruby_version: 2.7.5
